fb:
  appId:  616184c44f761f5499b2ee8048c6ef86
  appSecret:  616184c44f761f5499b2ee8048c6ef86
  verifyToken : AQIC5wM2LY4Sfcxm7uOcT8A6sQheqWcY19Py3BPRWvMAAJTSQACMDEAAlNLABQtNjQ1NDA3MDA2MzE0MzU5ODEyMg
  pageAccessToken: EAAd4oZBaNRNsBALVfOBPrWYSETrcxcZAqM9mzsKhybrT6K91J0d1lRsGEmDYo1FQw8eYlYqy8fvQ1mzGnhb7xifZBnprvWH7Jt3xZA3ZBOvDsLdXX4SI00NMKIIwAjgMsKJpSbHmSeNbwUZCAZCmOQJEJhZAstXCUdVglsPFMD521wZDZD

logging:
  level:
    com:
      github:
        messenger4j: DEBUG        
questions:
  properties:
    file: /app/config/questions.properties